"""HTTP contract and error type for custom photo avatars.

The web client (``app/web``) builds against these shapes, so treat every field
name, status literal and error code here as a published contract: add fields,
never rename or repurpose them.

The provider's own avatar id is never part of this contract. The API speaks only
in opaque AI4IA record ids (32 lowercase hex characters); the provider id stays
server-side, so a client can neither learn nor supply it.
"""
from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Literal, Protocol

from pydantic import BaseModel, ConfigDict, Field

if TYPE_CHECKING:
    from ..auth.base import AuthenticatedUser

# Lifecycle of one avatar record as the client sees it.
#   creating    reserved; the provider create outcome is not recorded yet
#   generating  the provider accepted the request and has not finished
#   confirming  the create outcome is unknown; a status read reconciles it
#   ready       the provider succeeded and the preview is stored
#   failed      terminal failure; ``failure.code`` says why
#   deleting    deletion started; repeating DELETE finishes it
PhotoAvatarStatus = Literal["creating", "generating", "confirming", "ready", "failed", "deleting"]
TERMINAL_STATUSES: frozenset[str] = frozenset({"ready", "failed"})

PhotoAvatarFailureCode = Literal[
    "provider_rejected",
    "provider_failed",
    "provider_throttled",
    "provider_forbidden",
    "not_created",
    "provider_missing",
    "preview_rejected",
    "project_unavailable",
]
FAILURE_MESSAGES: dict[str, str] = {
    "provider_rejected": "The avatar service did not accept this description.",
    "provider_failed": "The avatar service could not generate this avatar.",
    "provider_throttled": "The avatar service is busy. Try again later.",
    "provider_forbidden": "The avatar service refused this request for this deployment.",
    "not_created": "The avatar was not created.",
    "provider_missing": "The avatar no longer exists in the avatar service.",
    "preview_rejected": "The generated preview failed validation and was not stored.",
    "project_unavailable": "The avatar project is unavailable.",
}

# Why creation is or is not available right now. Display-only: the server
# re-checks the same predicate when a create executes.
AvailabilityReason = Literal[
    "available",
    "disabled",
    "storage_unavailable",
    "residency_unsupported",
    "policy_denied",
    "policy_unavailable",
    "capability_unavailable",
    "capability_unknown",
]

ReportReason = Literal["impersonation", "minor", "sexual", "hateful", "violent", "other"]
REPORT_REASONS: tuple[ReportReason, ...] = (
    "impersonation", "minor", "sexual", "hateful", "violent", "other",
)

AttestationStatementId = Literal["fictional", "adult", "notRealPerson"]
ATTESTATION_VERSION = "2026-09-25"
ATTESTATION_STATEMENTS: tuple[tuple[AttestationStatementId, str], ...] = (
    ("fictional", "The character is fictional and generated by AI."),
    ("adult", "The character is an adult."),
    ("notRealPerson", "The character is not modeled on a real or identifiable person."),
)

DISCLOSURE_LABEL = "AI-generated"
DISCLOSURE_TEXT = (
    "This avatar is a synthetic likeness generated by AI. It does not depict a real person."
)
# Named on Microsoft Learn's Limited Access page for text to speech ("Report
# abuse ... here"). The in-app report is the operator's own feedback channel.
MICROSOFT_REPORT_URL = "https://aka.ms/reportabuse"

DISPLAY_NAME_MAX_CHARS = 60
# A coarse schema ceiling only. The enforced prompt bound is the catalog's
# ``promptMaxChars`` in UTF-16 code units, the unit the APIM policy measures.
PROMPT_SCHEMA_MAX_CHARS = 4000
REPORT_DETAILS_MAX_CHARS = 1000
RECORD_ID_PATTERN = r"^[0-9a-f]{32}$"


class _Contract(BaseModel):
    model_config = ConfigDict(extra="forbid")


class PhotoAvatarAttestation(_Contract):
    """The user's statement about the character they describe. All three must be true."""

    version: str = Field(min_length=1, max_length=32)
    fictional: Literal[True]
    adult: Literal[True]
    notRealPerson: Literal[True]


class CreatePhotoAvatarRequest(_Contract):
    """``POST /api/photo-avatars``. Attribute values come from ``GET /config``."""

    displayName: str = Field(min_length=1, max_length=DISPLAY_NAME_MAX_CHARS)
    prompt: str = Field(min_length=1, max_length=PROMPT_SCHEMA_MAX_CHARS)
    gender: str | None = Field(default=None, max_length=64)
    age: str | None = Field(default=None, max_length=64)
    ethnicity: str | None = Field(default=None, max_length=64)
    style: str | None = Field(default=None, max_length=64)
    attestation: PhotoAvatarAttestation


class PhotoAvatarReportRequest(_Contract):
    """``POST /api/photo-avatars/{id}/reports``."""

    reason: ReportReason
    details: str | None = Field(default=None, max_length=REPORT_DETAILS_MAX_CHARS)


class PhotoAvatarAttributes(_Contract):
    gender: str | None = None
    age: str | None = None
    ethnicity: str | None = None
    style: str | None = None


class PhotoAvatarFailure(_Contract):
    code: PhotoAvatarFailureCode
    message: str


class PhotoAvatarPreview(_Contract):
    url: str
    contentType: Literal["image/png"] = "image/png"
    width: int
    height: int
    bytes: int


class PhotoAvatarDisclosure(_Contract):
    aiGenerated: Literal[True] = True
    label: str = DISCLOSURE_LABEL


class PhotoAvatarCost(_Contract):
    """Estimate recorded when the create was dispatched; never repriced later."""

    currency: str = "USD"
    estimatedUsd: float | None = None
    known: bool = False
    priceVersion: str | None = None
    basis: Literal["per_avatar"] = "per_avatar"


class PhotoAvatar(_Contract):
    """One avatar the caller owns."""

    id: str
    displayName: str
    prompt: str
    attributes: PhotoAvatarAttributes
    status: PhotoAvatarStatus
    failure: PhotoAvatarFailure | None = None
    preview: PhotoAvatarPreview | None = None
    disclosure: PhotoAvatarDisclosure = Field(default_factory=PhotoAvatarDisclosure)
    cost: PhotoAvatarCost = Field(default_factory=PhotoAvatarCost)
    # Ready and the feature is currently available. Later phases gate use on it.
    usable: bool = False
    reported: bool = False
    # A live session reported that this avatar failed verification. Live use is
    # refused (``usable`` is false) until a later status read re-verifies it.
    needsReverification: bool = False
    createdAt: datetime
    updatedAt: datetime
    readyAt: datetime | None = None


class PhotoAvatarList(_Contract):
    avatars: list[PhotoAvatar]


class PhotoAvatarLimits(_Contract):
    maxAvatars: int
    avatarCount: int
    maxCreationsPerDay: int
    creationsInLastDay: int
    # When the rolling daily window next frees a creation, if it is full.
    nextCreationAt: datetime | None = None
    promptMaxChars: int
    displayNameMaxChars: int = DISPLAY_NAME_MAX_CHARS


class PhotoAvatarAttributeOptions(_Contract):
    gender: list[str]
    age: list[str]
    ethnicity: list[str]
    style: list[str]


class PhotoAvatarAttestationStatement(_Contract):
    id: AttestationStatementId
    text: str


class PhotoAvatarAttestationInfo(_Contract):
    version: str
    statements: list[PhotoAvatarAttestationStatement]


class PhotoAvatarDisclosureInfo(_Contract):
    label: str
    text: str


class PhotoAvatarPricing(_Contract):
    currency: str
    estimatedUsdPerAvatar: float | None = None
    known: bool
    priceVersion: str | None = None


class PhotoAvatarFeedback(_Contract):
    reasons: list[ReportReason]
    detailsMaxChars: int
    microsoftReportUrl: str


class PhotoAvatarConfig(_Contract):
    """``GET /api/photo-avatars/config``: display posture only, never enforcement.

    When the feature is disabled only ``enabled``, ``available``, ``reason`` and
    ``canCreate`` are populated.
    """

    enabled: bool
    available: bool
    reason: AvailabilityReason
    # Available and under both limits.
    canCreate: bool
    limits: PhotoAvatarLimits | None = None
    attributes: PhotoAvatarAttributeOptions | None = None
    attestation: PhotoAvatarAttestationInfo | None = None
    disclosure: PhotoAvatarDisclosureInfo | None = None
    pricing: PhotoAvatarPricing | None = None
    feedback: PhotoAvatarFeedback | None = None

    @classmethod
    def disabled(cls) -> PhotoAvatarConfig:
        return cls(enabled=False, available=False, reason="disabled", canCreate=False)


class PhotoAvatarReportReceipt(_Contract):
    id: str
    avatarId: str
    reason: ReportReason
    createdAt: datetime


def attestation_info() -> PhotoAvatarAttestationInfo:
    return PhotoAvatarAttestationInfo(
        version=ATTESTATION_VERSION,
        statements=[
            PhotoAvatarAttestationStatement(id=identifier, text=text)
            for identifier, text in ATTESTATION_STATEMENTS
        ],
    )


def disclosure_info() -> PhotoAvatarDisclosureInfo:
    return PhotoAvatarDisclosureInfo(label=DISCLOSURE_LABEL, text=DISCLOSURE_TEXT)


def feedback_info() -> PhotoAvatarFeedback:
    return PhotoAvatarFeedback(
        reasons=list(REPORT_REASONS),
        detailsMaxChars=REPORT_DETAILS_MAX_CHARS,
        microsoftReportUrl=MICROSOFT_REPORT_URL,
    )


class PhotoAvatarError(Exception):
    """A refusal rendered with the shared error body and a stable ``code``.

    ``reason`` carries an :data:`AvailabilityReason` for 503 unavailability so a
    client can explain it without parsing ``detail``.
    """

    def __init__(
        self,
        status: int,
        code: str,
        detail: str,
        *,
        retry_after: int | None = None,
        reason: str | None = None,
    ) -> None:
        super().__init__(detail)
        self.status = status
        self.code = code
        self.detail = detail
        self.retry_after = retry_after
        self.reason = reason


class PhotoAvatarApi(Protocol):
    """What the router needs; implemented by :class:`~.service.PhotoAvatarService`."""

    async def config(self, user: AuthenticatedUser) -> PhotoAvatarConfig: ...

    async def list(self, user: AuthenticatedUser) -> PhotoAvatarList: ...

    async def create(
        self, user: AuthenticatedUser, request: CreatePhotoAvatarRequest,
    ) -> PhotoAvatar: ...

    async def get(self, user: AuthenticatedUser, avatar_id: str) -> PhotoAvatar: ...

    async def preview(self, user: AuthenticatedUser, avatar_id: str) -> bytes: ...

    async def delete(self, user: AuthenticatedUser, avatar_id: str) -> None: ...

    async def report(
        self, user: AuthenticatedUser, avatar_id: str, request: PhotoAvatarReportRequest,
    ) -> PhotoAvatarReportReceipt: ...
