"""The ``generate_image`` synthetic capability.

Mirrors the document ``run_code`` / ``export_document`` capabilities
(:mod:`ai4ia_api.library.compute_capability`): a function schema + an async
handler injected into :func:`~ai4ia_api.agents.runtime.run_agent_turn` as
``extra_tools`` / ``extra_handlers``. This makes image generation a tool **any
agent can attach** — decoupled from any single agent — so users compose it into
their own personas (the same pattern intended for video and document processing).

Why synthetic (closure-bound) rather than a registry tool: generation needs
real services (the model gateway, the catalog, the entitlement gate, the usage
meter, and durable blob storage), but a registry tool handler only receives
``(args, ToolContext)`` and an agent turn runs with an empty context. So the
capability is built per turn with its services + the authenticated ``user_id``
captured in a closure — a tool argument can only ever carry the prompt/model/size,
never spoof the user.

The generated bytes are far larger than the runtime's 8 KB tool-result cap, so
the handler **persists** the image to per-user blob storage and returns only a
small reference (the ``artifact_id``). The reference is also appended to a
per-turn ``sink`` that the chat router drains onto the assistant message as a
:class:`~ai4ia_api.sessions.models.MessageAttachment`, which the browser renders
by fetching the bytes from the authenticated serve endpoint.
"""
from __future__ import annotations

import asyncio
import base64
import logging
from collections.abc import Awaitable, Callable
from typing import Any
from uuid import uuid4

from ..agents.tool_exec import ToolContext
from ..catalog import ModelCatalog
from ..entitlements.service import EntitlementService
from ..sessions.models import MessageAttachment
from ..usage.models import UsageStatus
from ..usage.service import UsageService
from .artifacts import ImageArtifactStore
from .service import ImageGenerationError, ImageGenerationService

logger = logging.getLogger(__name__)

GENERATE_IMAGE_TOOL_NAME = "generate_image"

# Per-turn budget (on top of the runtime's global tool-call budget). Image
# generation is a slow, metered, paid call, so a turn may produce only a few.
MAX_IMAGES_PER_TURN = 3

# Length bounds for sanitized scalar fields returned to / stored from the model.
_FIELD_LIMIT = 200
_PROMPT_KEEP = 400

Handler = Callable[[dict[str, Any], ToolContext], Awaitable[dict[str, Any]]]


def _one_line(text: str, limit: int = _FIELD_LIMIT) -> str:
    return (text or "").replace("\n", " ").replace("\r", " ").strip()[:limit]


def _image_model_ids(catalog: ModelCatalog) -> list[str]:
    return [m.id for m in catalog.models if m.category == "image"]


def build_image_capability(
    *,
    image_service: ImageGenerationService,
    artifact_store: ImageArtifactStore,
    entitlements: EntitlementService,
    metering: UsageService,
    catalog: ModelCatalog,
    user_id: str,
    session_id: str,
    sink: list[MessageAttachment],
) -> tuple[list[dict[str, Any]], dict[str, Handler]]:
    """Build the ``generate_image`` tool bound to ``user_id``.

    Returns ``(extra_tools, extra_handlers)`` ready to merge into
    :func:`run_agent_turn`. Successful generations are appended to ``sink`` (the
    chat router attaches them to the assistant message) and metered to
    ``session_id``. Governance — entitlement gate, image-category-only model,
    size allowlist, payload caps — is shared with the HTTP endpoint via
    :class:`ImageGenerationService` and the per-turn entitlement check here.
    """
    budget = {"used": 0}
    image_ids = _image_model_ids(catalog)
    models_hint = (
        f" Available image models: {', '.join(image_ids)}." if image_ids else ""
    )

    schema: dict[str, Any] = {
        "type": "function",
        "function": {
            "name": GENERATE_IMAGE_TOOL_NAME,
            "description": (
                "Generate an image from a text prompt and show it to the user. Use "
                "this whenever the user asks to create, draw, render, or illustrate a "
                "picture. The image is displayed to the user automatically — you do "
                "NOT receive the pixels, only a confirmation, so never try to "
                "describe or transcribe the generated image bytes." + models_hint
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": (
                            "A detailed description of the image to generate."
                        ),
                    },
                    "model": {
                        "type": "string",
                        "description": (
                            "Optional image model id to use. Omit to use the default "
                            "image model."
                        ),
                    },
                    "size": {
                        "type": "string",
                        "enum": ["1024x1024", "1024x1536", "1536x1024", "auto"],
                        "description": (
                            "Optional output size. Square (1024x1024) by default; use "
                            "1024x1536 for portrait or 1536x1024 for landscape."
                        ),
                    },
                    "quality": {
                        "type": "string",
                        "enum": ["auto", "low", "medium", "high"],
                        "description": (
                            "Optional rendering quality. Higher quality costs more and "
                            "takes longer; omit (auto) to let the provider choose."
                        ),
                    },
                },
                "required": ["prompt"],
                "additionalProperties": False,
            },
        },
    }

    async def _handler(args: dict[str, Any], ctx: ToolContext) -> dict[str, Any]:
        if budget["used"] >= MAX_IMAGES_PER_TURN:
            return {"error": "image generation budget exhausted for this turn."}
        prompt = str(args.get("prompt") or "").strip()
        if not prompt:
            return {"error": "prompt must be a non-empty string."}
        model = args.get("model") if isinstance(args.get("model"), str) else None
        size = args.get("size") if isinstance(args.get("size"), str) else None
        quality = args.get("quality") if isinstance(args.get("quality"), str) else None
        budget["used"] += 1

        # Entitlement gate (mirrors the HTTP endpoint): a disabled user is blocked
        # and any admin-set rate/budget limit applies before we spend on a call.
        decision = await entitlements.check(user_id)
        if not decision.allowed:
            return {"error": _one_line(decision.reason or "image generation is not permitted.")}

        try:
            result = await image_service.generate(
                prompt=prompt,
                model=model,
                size=size,
                quality=quality,
                n=1,
                correlation_id=ctx.correlation_id,
            )
        except ImageGenerationError as exc:
            return {"error": _one_line(exc.detail)}
        except Exception:  # noqa: BLE001 - a tool must never crash the turn
            logger.warning("generate_image unexpected error user=%s", user_id, exc_info=True)
            return {"error": "Image generation failed."}

        meter_status: UsageStatus = "error"
        try:
            try:
                raw = base64.b64decode(result.images_b64[0])
            except Exception:  # noqa: BLE001
                logger.warning("generate_image decode error user=%s", user_id, exc_info=True)
                return {"error": "Generated image could not be decoded."}

            artifact_id = uuid4().hex
            try:
                await artifact_store.put(user_id, artifact_id, raw)
            except asyncio.CancelledError:
                meter_status = "cancelled"
                raise
            except Exception:  # noqa: BLE001
                logger.warning("generate_image store error user=%s", user_id, exc_info=True)
                return {"error": "Generated image could not be stored."}
            sink.append(
                MessageAttachment(
                    id=artifact_id,
                    kind="image",
                    mimeType="image/png",
                    prompt=prompt[:_PROMPT_KEEP],
                    model=result.model_id,
                    size=result.size,
                    quality=result.quality,
                )
            )
            meter_status = "complete"
        finally:
            # Provider work remains chargeable when local decode/persistence fails.
            await metering.record_completion(
                user_id=user_id,
                session_id=session_id,
                model_id=result.model_id,
                deployment=result.deployment,
                usage=result.usage,
                status=meter_status,
                provider_completed=True,
                correlation_id=ctx.correlation_id,
            )

        return {
            "status": "generated",
            "artifact_id": artifact_id,
            "model": _one_line(result.model_id),
            "size": _one_line(result.size),
            "quality": _one_line(result.quality),
            "note": (
                "The image was generated and is shown to the user. You do not have "
                "the pixels; do not describe the image contents."
            ),
        }

    return [schema], {GENERATE_IMAGE_TOOL_NAME: _handler}
