"""The ``generate_image`` synthetic capability.

Mirrors the document ``run_code`` / ``export_document`` capabilities
(:mod:`ai4ia_api.library.compute_capability`): a function schema + an async
handler injected into :func:`~ai4ia_api.agents.runtime.run_agent_turn` as
``extra_tools`` / ``extra_handlers``. This makes image generation a tool **any
agent can attach** — decoupled from any single agent — so users compose it into
their own personas (the same pattern intended for video and document processing).

Why synthetic (closure-bound) rather than a registry tool: generation needs
real services (the model gateway, the catalog, the entitlement gate, the usage
meter, and durable blob storage), but a registry tool handler only receives
``(args, ToolContext)`` and an agent turn runs with an empty context. So the
capability is built per turn with its services + the authenticated ``user_id``
captured in a closure — a tool argument can only ever carry the prompt/model/size,
never spoof the user.

The generated bytes are far larger than the runtime's 8 KB tool-result cap, so
the handler **persists** the image to per-user blob storage and returns only a
small reference (the ``artifact_id``). The reference is also appended to a
per-turn ``sink`` that the chat router drains onto the assistant message as a
:class:`~ai4ia_api.sessions.models.MessageAttachment`, which the browser renders
by fetching the bytes from the authenticated serve endpoint.
"""
from __future__ import annotations

import asyncio
import base64
import logging
from collections.abc import Awaitable, Callable
from typing import Any
from uuid import uuid4

from ..agents.tool_exec import ToolContext
from ..catalog import DeploymentOption, ModelCatalog
from ..entitlements.service import EntitlementService
from ..sessions.models import MessageAttachment
from ..sessions.models import ImageGenerationPreferences
from ..usage.models import UsageStatus, UsageTarget
from ..usage.pricing import load_pricing
from ..usage.service import UsageService
from .artifacts import ImageArtifactStore
from .service import ImageGenerationError, ImageGenerationService

logger = logging.getLogger(__name__)

GENERATE_IMAGE_TOOL_NAME = "generate_image"

# Per-turn budget (on top of the runtime's global tool-call budget). Image
# generation is a slow, metered, paid call, so a turn may produce only a few.
MAX_IMAGES_PER_TURN = 3

# Length bounds for sanitized scalar fields returned to / stored from the model.
_FIELD_LIMIT = 200
_PROMPT_KEEP = 400

Handler = Callable[[dict[str, Any], ToolContext], Awaitable[dict[str, Any]]]


def _one_line(text: str, limit: int = _FIELD_LIMIT) -> str:
    return (text or "").replace("\n", " ").replace("\r", " ").strip()[:limit]


def _image_model_ids(catalog: ModelCatalog) -> list[str]:
    return [m.id for m in catalog.models if m.category == "image"]


def build_image_capability(
    *,
    image_service: ImageGenerationService,
    artifact_store: ImageArtifactStore,
    entitlements: EntitlementService,
    metering: UsageService,
    catalog: ModelCatalog,
    user_id: str,
    session_id: str,
    sink: list[MessageAttachment],
    preferences: ImageGenerationPreferences | None = None,
) -> tuple[list[dict[str, Any]], dict[str, Handler]]:
    """Build the ``generate_image`` tool bound to ``user_id``.

    Returns ``(extra_tools, extra_handlers)`` ready to merge into
    :func:`run_agent_turn`. Successful generations are appended to ``sink`` (the
    chat router attaches them to the assistant message) and metered to
    ``session_id``. Governance — entitlement gate, image-category-only model,
    size allowlist, payload caps — is shared with the HTTP endpoint via
    :class:`ImageGenerationService` and the per-turn entitlement check here.
    """
    budget = {"used": 0}
    image_ids = _image_model_ids(catalog)
    models_hint = (
        f" Available image models: {', '.join(image_ids)}." if image_ids else ""
    )
    constrained = [
        f"{model.id} supports sizes {', '.join(model.imageSizes or [])} and "
        f"qualities {', '.join(model.imageQualities or [])}"
        for model in catalog.models
        if model.category == "image" and (model.imageSizes or model.imageQualities)
    ]
    constraints_hint = (
        f" Provider-specific constraints: {'; '.join(constrained)}." if constrained else ""
    )
    preferred = preferences or ImageGenerationPreferences()
    preference_hint = (
        f" This conversation currently selects {', '.join(preferred.models)}, size "
        f"{preferred.size}, quality {preferred.quality}. Generate the same prompt "
        "with every selected model; the user may change this selection between turns."
        if preferred.models
        else ""
    )

    schema: dict[str, Any] = {
        "type": "function",
        "function": {
            "name": GENERATE_IMAGE_TOOL_NAME,
            "description": (
                "Generate an image from a text prompt and show it to the user. Use "
                "this whenever the user asks to create, draw, render, or illustrate a "
                "picture. The image is displayed to the user automatically — you do "
                "NOT receive the pixels, only a confirmation, so never try to "
                "describe or transcribe the generated image bytes."
                + models_hint
                + constraints_hint
                + preference_hint
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "prompt": {
                        "type": "string",
                        "description": (
                            "A detailed description of the image to generate."
                        ),
                    },
                    "model": {
                        "type": "string",
                        "description": (
                            "Optional single image model id. Ignored when the "
                            "conversation already has selected image models."
                        ),
                    },
                    "models": {
                        "type": "array",
                        "items": {"type": "string"},
                        "maxItems": MAX_IMAGES_PER_TURN,
                        "uniqueItems": True,
                        "description": (
                            "Optional image model ids for a side-by-side comparison "
                            "of the same prompt. Ignored when the conversation already "
                            "has selected image models."
                        ),
                    },
                    "size": {
                        "type": "string",
                        "enum": [
                            "1024x1024",
                            "1024x1440",
                            "1440x1024",
                            "1024x1536",
                            "1536x1024",
                            "auto",
                        ],
                        "description": (
                            "Optional output size. Square (1024x1024) by default; use "
                            "a portrait/landscape size supported by the selected model."
                        ),
                    },
                    "quality": {
                        "type": "string",
                        "enum": ["auto", "low", "medium", "high"],
                        "description": (
                            "Optional rendering quality. Higher quality costs more and "
                            "takes longer; omit (auto) to let the provider choose."
                        ),
                    },
                },
                "required": ["prompt"],
                "additionalProperties": False,
            },
        },
    }

    async def _handler(args: dict[str, Any], ctx: ToolContext) -> dict[str, Any]:
        prompt = str(args.get("prompt") or "").strip()
        if not prompt:
            return {"error": "prompt must be a non-empty string."}
        requested_model = (
            args.get("model") if isinstance(args.get("model"), str) else None
        )
        requested_models = (
            [model for model in args.get("models", []) if isinstance(model, str)]
            if isinstance(args.get("models"), list)
            else []
        )
        candidates: list[str] = list(preferred.models)
        if not candidates:
            candidates.extend(requested_models)
            if requested_model:
                candidates.append(requested_model)
        selected_models: list[str] = list(dict.fromkeys(candidates))
        # An empty list preserves the service's existing default-model behavior.
        models_to_run: list[str | None] = (
            [*selected_models] if selected_models else [None]
        )
        if (
            len(models_to_run) > MAX_IMAGES_PER_TURN
            or budget["used"] + len(models_to_run) > MAX_IMAGES_PER_TURN
        ):
            return {
                "error": (
                    f"at most {MAX_IMAGES_PER_TURN} images may be generated "
                    "in one turn."
                )
            }
        requested_size = args.get("size") if isinstance(args.get("size"), str) else None
        requested_quality = (
            args.get("quality") if isinstance(args.get("quality"), str) else None
        )
        size = preferred.size or requested_size
        quality = preferred.quality or requested_quality
        budget["used"] += len(models_to_run)

        # Entitlement gate (mirrors the HTTP endpoint): a disabled user is blocked
        # and any admin-set rate/budget limit applies before we spend on a call.
        decision = await entitlements.check(user_id)
        if not decision.allowed:
            return {"error": _one_line(decision.reason or "image generation is not permitted.")}

        generated: list[dict[str, Any]] = []
        errors: list[str] = []

        def scoped_error(model_id: str | None, detail: str) -> str:
            if len(models_to_run) == 1:
                return detail
            return f"{model_id or 'default image model'}: {detail}"

        def append_failure(
            *,
            model_id: str | None,
            detail: str,
            provider: str | None = None,
            deployment: DeploymentOption | None = None,
            failure_size: str | None = None,
            failure_quality: str | None = None,
            provider_completed: bool = False,
        ) -> None:
            estimate = (
                load_pricing().estimate_image(
                    model_id,
                    size=failure_size,
                    quality=failure_quality,
                    count=1,
                )
                if provider_completed and model_id
                else None
            )
            sink.append(
                MessageAttachment(
                    id=uuid4().hex,
                    kind="image_error",
                    mimeType="application/problem+json",
                    prompt=prompt[:_PROMPT_KEEP],
                    model=model_id,
                    provider=provider,
                    deployment=(
                        deployment.deploymentName if deployment is not None else None
                    ),
                    region=deployment.region if deployment is not None else None,
                    dataZone=deployment.dataZone if deployment is not None else None,
                    residency=deployment.residency if deployment is not None else None,
                    size=failure_size,
                    quality=failure_quality,
                    costKnown=estimate.known if estimate is not None else False,
                    estimatedCostUsd=(
                        estimate.micro_usd / 1_000_000
                        if estimate is not None
                        and estimate.micro_usd is not None
                        else None
                    ),
                    pricingBasis=(
                        estimate.pricing_basis if estimate is not None else None
                    ),
                    priceVersion=estimate.version if estimate is not None else None,
                    status="error",
                    error=_one_line(detail),
                )
            )

        for model in models_to_run:
            try:
                result = await image_service.generate(
                    prompt=prompt,
                    model=model,
                    size=size,
                    quality=quality,
                    n=1,
                    correlation_id=ctx.correlation_id,
                )
            except ImageGenerationError as exc:
                if exc.provider_completion is not None:
                    completion = exc.provider_completion
                    await metering.record_completion(
                        user_id=user_id,
                        session_id=session_id,
                        model_id=completion.model_id,
                        target=UsageTarget.from_deployment(
                            completion.deployment, provider=completion.provider
                        ),
                        usage=completion.usage,
                        status="error",
                        provider_completed=True,
                        correlation_id=ctx.correlation_id,
                        billable_units=completion.billable_units,
                        billing_unit=completion.billing_unit,
                        image_size=completion.image_size,
                        image_quality=completion.image_quality,
                    )
                    append_failure(
                        model_id=completion.model_id,
                        detail=exc.detail,
                        provider=completion.provider,
                        deployment=completion.deployment,
                        failure_size=completion.image_size,
                        failure_quality=completion.image_quality,
                        provider_completed=True,
                    )
                else:
                    append_failure(
                        model_id=model,
                        detail=exc.detail,
                        failure_size=size,
                        failure_quality=quality,
                    )
                errors.append(scoped_error(model, _one_line(exc.detail)))
                continue
            except Exception:  # noqa: BLE001 - a tool must never crash the turn
                logger.warning(
                    "generate_image unexpected error user=%s model=%s",
                    user_id,
                    model,
                    exc_info=True,
                )
                append_failure(
                    model_id=model,
                    detail="Image generation failed.",
                    failure_size=size,
                    failure_quality=quality,
                )
                errors.append(scoped_error(model, "Image generation failed."))
                continue

            meter_status: UsageStatus = "error"
            artifact_id: str | None = None
            try:
                try:
                    raw = base64.b64decode(result.images_b64[0])
                except Exception:  # noqa: BLE001
                    logger.warning(
                        "generate_image decode error user=%s model=%s",
                        user_id,
                        result.model_id,
                        exc_info=True,
                    )
                    errors.append(
                        scoped_error(
                            result.model_id,
                            "Generated image could not be decoded.",
                        )
                    )
                    append_failure(
                        model_id=result.model_id,
                        detail="Generated image could not be decoded.",
                        provider=result.provider,
                        deployment=result.deployment,
                        failure_size=result.size,
                        failure_quality=result.quality,
                        provider_completed=True,
                    )
                    continue

                artifact_id = uuid4().hex
                try:
                    await artifact_store.put(user_id, artifact_id, raw)
                except asyncio.CancelledError:
                    meter_status = "cancelled"
                    raise
                except Exception:  # noqa: BLE001
                    logger.warning(
                        "generate_image store error user=%s model=%s",
                        user_id,
                        result.model_id,
                        exc_info=True,
                    )
                    errors.append(
                        scoped_error(
                            result.model_id,
                            "Generated image could not be stored.",
                        )
                    )
                    append_failure(
                        model_id=result.model_id,
                        detail="Generated image could not be stored.",
                        provider=result.provider,
                        deployment=result.deployment,
                        failure_size=result.size,
                        failure_quality=result.quality,
                        provider_completed=True,
                    )
                    continue
                estimate = load_pricing().estimate_image(
                    result.model_id,
                    size=result.size,
                    quality=result.quality,
                    count=1,
                )
                estimated_cost = (
                    estimate.micro_usd / 1_000_000
                    if estimate.micro_usd is not None
                    else None
                )
                sink.append(
                    MessageAttachment(
                        id=artifact_id,
                        kind="image",
                        mimeType="image/png",
                        prompt=prompt[:_PROMPT_KEEP],
                        model=result.model_id,
                        provider=result.provider,
                        deployment=result.deployment.deploymentName,
                        region=result.deployment.region,
                        dataZone=result.deployment.dataZone,
                        residency=result.deployment.residency,
                        size=result.size,
                        quality=result.quality,
                        costKnown=estimate.known,
                        estimatedCostUsd=estimated_cost,
                        pricingBasis=estimate.pricing_basis,
                        priceVersion=estimate.version,
                        status="complete",
                    )
                )
                generated.append(
                    {
                        "artifact_id": artifact_id,
                        "model": _one_line(result.model_id),
                        "size": _one_line(result.size),
                        "quality": _one_line(result.quality),
                        "cost_known": estimate.known,
                        "estimated_cost_usd": estimated_cost,
                    }
                )
                meter_status = "complete"
            finally:
                # Provider work remains chargeable when local decode/persistence fails.
                await metering.record_completion(
                    user_id=user_id,
                    session_id=session_id,
                    model_id=result.model_id,
                    target=UsageTarget.from_deployment(
                        result.deployment, provider=result.provider
                    ),
                    usage=result.usage,
                    status=meter_status,
                    provider_completed=True,
                    correlation_id=ctx.correlation_id,
                    billable_units=1,
                    billing_unit="image",
                    image_size=result.size,
                    image_quality=result.quality,
                )

        if not generated:
            return {"error": "; ".join(errors) or "Image generation failed."}
        first = generated[0]
        return {
            "status": "generated",
            # Preserve the single-image result fields for existing clients.
            "artifact_id": first["artifact_id"],
            "model": first["model"],
            "size": first["size"],
            "quality": first["quality"],
            "artifacts": generated,
            "errors": errors,
            "note": (
                f"{len(generated)} image(s) were generated and shown to the user. "
                "You do not have the pixels; do not describe the image contents."
            ),
        }

    return [schema], {GENERATE_IMAGE_TOOL_NAME: _handler}
