/* GENERATED by scripts/gen-voice-provider-catalog.py from infra/voice-providers.json. Do not edit by hand. */

export const voiceProviderCatalog = {
  "$schema": "./voice-providers.schema.json",
  "_comment": "GENERATED by scripts/gen-voice-provider-catalog.py from infra/voice-providers.json. Do not edit by hand.",
  "defaultProviderId": "azure_openai",
  "providers": [
    {
      "id": "azure_openai",
      "displayName": "Azure OpenAI Realtime",
      "displayLabel": "Azure OpenAI",
      "description": "Runtime-enabled realtime models from infra/models.json, filtered by the server-selected protocol.",
      "transport": "websocket",
      "selectionMode": "deployment_catalog",
      "endpointPath": "/openai/realtime",
      "modelCatalogRef": {
        "sourceJson": "infra/models.json",
        "filter": {
          "category": "realtime",
          "runtimeEnabled": true
        },
        "defaultModelId": "gpt-realtime"
      },
      "sessionDefaults": {
        "voice": "alloy",
        "inputTranscription": "whisper-1",
        "turnDetection": "server_vad",
        "interruptResponse": true,
        "autoTruncate": false
      },
      "capabilities": {
        "voices": {
          "kind": "openai-realtime",
          "default": "alloy",
          "options": [
            "alloy",
            "ash",
            "ballad",
            "coral",
            "echo",
            "sage",
            "shimmer",
            "verse",
            "marin",
            "cedar"
          ]
        },
        "inputTranscription": {
          "provider": "openai",
          "default": "whisper-1",
          "options": [
            "whisper-1"
          ]
        },
        "turnDetection": {
          "default": "server_vad",
          "options": [
            "server_vad",
            "semantic_vad"
          ]
        },
        "interruption": {
          "interruptResponse": true,
          "autoTruncate": false
        },
        "customVoice": {
          "enabled": false,
          "allowEndpointIds": false,
          "allowLexicons": false,
          "allowPersonalVoice": false
        }
      }
    },
    {
      "id": "speech_voice_live",
      "displayName": "Azure Speech Voice Live",
      "displayLabel": "Azure Speech",
      "description": "Catalog-driven managed Voice Live provider backed by Azure Speech in Foundry Tools.",
      "transport": "websocket",
      "selectionMode": "managed_model_catalog",
      "endpointPath": "/voice-live/realtime",
      "defaultManagedModelId": "gpt-realtime",
      "managedModels": [
        {
          "id": "gpt-realtime",
          "displayName": "GPT Realtime",
          "description": "Native-audio realtime model with GPT-4o transcription.",
          "profile": "native_audio",
          "inputTranscription": {
            "provider": "openai",
            "model": "gpt-4o-transcribe"
          },
          "samplingSupported": true,
          "apiVersion": "2026-04-10",
          "initialRegion": "eastus2",
          "audioFormat": "pcm16",
          "sampleRateHz": 24000
        },
        {
          "id": "gpt-realtime-mini",
          "displayName": "GPT Realtime Mini",
          "description": "Lower-cost native-audio realtime model with GPT-4o transcription.",
          "profile": "native_audio",
          "inputTranscription": {
            "provider": "openai",
            "model": "gpt-4o-transcribe"
          },
          "samplingSupported": true,
          "apiVersion": "2026-04-10",
          "initialRegion": "eastus2",
          "audioFormat": "pcm16",
          "sampleRateHz": 24000
        },
        {
          "id": "gpt-realtime-1.5",
          "displayName": "GPT Realtime 1.5",
          "description": "Native-audio realtime 1.5 model with GPT-4o transcription.",
          "profile": "native_audio",
          "inputTranscription": {
            "provider": "openai",
            "model": "gpt-4o-transcribe"
          },
          "samplingSupported": true,
          "apiVersion": "2026-04-10",
          "initialRegion": "eastus2",
          "audioFormat": "pcm16",
          "sampleRateHz": 24000
        },
        {
          "id": "gpt-realtime-2.1",
          "displayName": "GPT Realtime 2.1",
          "description": "Native-audio realtime 2.1 model with GPT-4o transcription.",
          "profile": "native_audio",
          "inputTranscription": {
            "provider": "openai",
            "model": "gpt-4o-transcribe"
          },
          "samplingSupported": true,
          "apiVersion": "2026-04-10",
          "initialRegion": "eastus2",
          "audioFormat": "pcm16",
          "sampleRateHz": 24000
        },
        {
          "id": "gpt-realtime-2.1-mini",
          "displayName": "GPT Realtime 2.1 Mini",
          "description": "Lower-cost native-audio realtime 2.1 model with GPT-4o transcription.",
          "profile": "native_audio",
          "inputTranscription": {
            "provider": "openai",
            "model": "gpt-4o-transcribe"
          },
          "samplingSupported": true,
          "apiVersion": "2026-04-10",
          "initialRegion": "eastus2",
          "audioFormat": "pcm16",
          "sampleRateHz": 24000
        },
        {
          "id": "gpt-4.1",
          "displayName": "GPT-4.1",
          "description": "GPT-4.1 response model paired with the Azure Speech chain.",
          "profile": "azure_speech_chain",
          "inputTranscription": {
            "provider": "azure_speech",
            "model": "azure-speech"
          },
          "samplingSupported": true,
          "apiVersion": "2026-04-10",
          "initialRegion": "eastus2",
          "audioFormat": "pcm16",
          "sampleRateHz": 24000
        },
        {
          "id": "gpt-4.1-mini",
          "displayName": "GPT-4.1 Mini",
          "description": "GPT-4.1 Mini response model paired with the Azure Speech chain.",
          "profile": "azure_speech_chain",
          "inputTranscription": {
            "provider": "azure_speech",
            "model": "azure-speech"
          },
          "samplingSupported": true,
          "apiVersion": "2026-04-10",
          "initialRegion": "eastus2",
          "audioFormat": "pcm16",
          "sampleRateHz": 24000
        },
        {
          "id": "gpt-5-mini",
          "displayName": "GPT-5 Mini",
          "description": "GPT-5 Mini response model paired with the Azure Speech chain.",
          "profile": "azure_speech_chain",
          "inputTranscription": {
            "provider": "azure_speech",
            "model": "azure-speech"
          },
          "samplingSupported": false,
          "apiVersion": "2026-04-10",
          "initialRegion": "eastus2",
          "audioFormat": "pcm16",
          "sampleRateHz": 24000
        },
        {
          "id": "gpt-5.1",
          "displayName": "GPT-5.1",
          "description": "GPT-5.1 response model paired with the Azure Speech chain.",
          "profile": "azure_speech_chain",
          "inputTranscription": {
            "provider": "azure_speech",
            "model": "azure-speech"
          },
          "samplingSupported": false,
          "apiVersion": "2026-04-10",
          "initialRegion": "eastus2",
          "audioFormat": "pcm16",
          "sampleRateHz": 24000
        },
        {
          "id": "gpt-5.2",
          "displayName": "GPT-5.2",
          "description": "GPT-5.2 response model paired with the Azure Speech chain.",
          "profile": "azure_speech_chain",
          "inputTranscription": {
            "provider": "azure_speech",
            "model": "azure-speech"
          },
          "samplingSupported": false,
          "reasoningEffort": "none",
          "apiVersion": "2026-04-10",
          "initialRegion": "eastus2",
          "audioFormat": "pcm16",
          "sampleRateHz": 24000
        },
        {
          "id": "gpt-5.4",
          "displayName": "GPT-5.4",
          "description": "GPT-5.4 response model paired with the Azure Speech chain.",
          "profile": "azure_speech_chain",
          "inputTranscription": {
            "provider": "azure_speech",
            "model": "azure-speech"
          },
          "samplingSupported": false,
          "reasoningEffort": "none",
          "apiVersion": "2026-04-10",
          "initialRegion": "eastus2",
          "audioFormat": "pcm16",
          "sampleRateHz": 24000
        },
        {
          "id": "gpt-5.6-terra",
          "displayName": "GPT-5.6 Terra",
          "description": "GPT-5.6 Terra response model paired with the Azure Speech chain.",
          "profile": "azure_speech_chain",
          "inputTranscription": {
            "provider": "azure_speech",
            "model": "azure-speech"
          },
          "samplingSupported": false,
          "reasoningEffort": "none",
          "apiVersion": "2026-04-10",
          "initialRegion": "eastus2",
          "audioFormat": "pcm16",
          "sampleRateHz": 24000
        },
        {
          "id": "gpt-5.6-luna",
          "displayName": "GPT-5.6 Luna",
          "description": "GPT-5.6 Luna response model paired with the Azure Speech chain.",
          "profile": "azure_speech_chain",
          "inputTranscription": {
            "provider": "azure_speech",
            "model": "azure-speech"
          },
          "samplingSupported": false,
          "reasoningEffort": "none",
          "apiVersion": "2026-04-10",
          "initialRegion": "eastus2",
          "audioFormat": "pcm16",
          "sampleRateHz": 24000
        }
      ],
      "sessionDefaults": {
        "voice": "en-US-Ava:DragonHDLatestNeural",
        "turnDetection": "azure_semantic_vad",
        "locale": "en-US",
        "noiseSuppression": "azure_deep_noise_suppression",
        "echoCancellation": "server_echo_cancellation",
        "interruptResponse": true,
        "autoTruncate": false
      },
      "capabilities": {
        "voices": {
          "kind": "azure-standard",
          "default": "en-US-Ava:DragonHDLatestNeural",
          "options": [
            "en-US-Ava:DragonHDLatestNeural",
            "en-US-AvaNeural",
            "en-US-AndrewNeural",
            "en-US-Brian:DragonHDLatestNeural",
            "en-US-Emma:DragonHDLatestNeural",
            "en-US-Jenny:DragonHDLatestNeural",
            "en-US-Ethan:MAI-Voice-2.1-Flash",
            "en-US-Grant:MAI-Voice-2.1-Flash",
            "en-US-Harper:MAI-Voice-2.1-Flash",
            "en-US-Iris:MAI-Voice-2.1-Flash",
            "en-US-Jasper:MAI-Voice-2.1-Flash",
            "en-US-Olivia:MAI-Voice-2.1-Flash",
            "en-US-Sage:MAI-Voice-2.1-Flash",
            "en-US-Ethan:MAI-Voice-2.1",
            "en-US-Grant:MAI-Voice-2.1",
            "en-US-Harper:MAI-Voice-2.1",
            "en-US-Iris:MAI-Voice-2.1",
            "en-US-Jasper:MAI-Voice-2.1",
            "en-US-Olivia:MAI-Voice-2.1",
            "en-US-Sage:MAI-Voice-2.1"
          ],
          "previewOptions": [
            "en-US-Ethan:MAI-Voice-2.1-Flash",
            "en-US-Grant:MAI-Voice-2.1-Flash",
            "en-US-Harper:MAI-Voice-2.1-Flash",
            "en-US-Iris:MAI-Voice-2.1-Flash",
            "en-US-Jasper:MAI-Voice-2.1-Flash",
            "en-US-Olivia:MAI-Voice-2.1-Flash",
            "en-US-Sage:MAI-Voice-2.1-Flash",
            "en-US-Ethan:MAI-Voice-2.1",
            "en-US-Grant:MAI-Voice-2.1",
            "en-US-Harper:MAI-Voice-2.1",
            "en-US-Iris:MAI-Voice-2.1",
            "en-US-Jasper:MAI-Voice-2.1",
            "en-US-Olivia:MAI-Voice-2.1",
            "en-US-Sage:MAI-Voice-2.1"
          ]
        },
        "inputTranscription": {
          "options": [
            {
              "model": "mai-transcribe-2",
              "displayName": "MAI Transcribe 2",
              "preview": true,
              "profiles": [
                "native_audio",
                "azure_speech_chain"
              ]
            }
          ]
        },
        "turnDetection": {
          "default": "azure_semantic_vad",
          "options": [
            "azure_semantic_vad",
            "azure_semantic_vad_multilingual"
          ]
        },
        "noiseSuppression": {
          "default": "azure_deep_noise_suppression",
          "options": [
            "azure_deep_noise_suppression"
          ]
        },
        "echoCancellation": {
          "default": "server_echo_cancellation",
          "options": [
            "server_echo_cancellation"
          ],
          "clientReference": {
            "preview": true,
            "apiVersion": "2026-07-15",
            "features": "client_ec_reference:true",
            "channels": 2
          }
        },
        "interruption": {
          "interruptResponse": true,
          "autoTruncate": false
        },
        "locale": {
          "default": "en-US",
          "options": [
            "en-US"
          ]
        },
        "customVoice": {
          "enabled": false,
          "allowEndpointIds": false,
          "allowLexicons": false,
          "allowPersonalVoice": false
        }
      }
    }
  ],
  "photoAvatars": {
    "displayName": "Azure Speech photo avatars",
    "description": "Custom photo avatars generated from a text description (Create with AI). Limited Access; default-off in AI4IA.",
    "homeRegion": "eastus2",
    "homeDataZone": "US",
    "apiVersion": "2023-12-01-preview",
    "requiredFeature": "CustomAvatar",
    "projectSuffix": "_PhotoAvatar",
    "baseModel": "vasa-1",
    "billingModelId": "photo-avatar-standard",
    "liveBillingModelId": "photo-avatar-realtime-standard",
    "promptMaxChars": 1000,
    "attributes": {
      "gender": [
        "Male",
        "Female"
      ],
      "age": [
        "YoungAdult",
        "MiddleAged",
        "Senior"
      ],
      "ethnicity": [
        "Asian",
        "White",
        "BlackAndAfricanAmerican",
        "SouthAsian",
        "MiddleEastern",
        "HispanicAndLatinx"
      ],
      "style": [
        "Realistic",
        "DigitalIllustration",
        "Stylized3D"
      ]
    },
    "preview": {
      "host": "stttssvcproduse2.blob.core.windows.net",
      "maxBytes": 8388608,
      "maxDimension": 4096,
      "contentTypes": [
        "application/octet-stream",
        "image/png"
      ]
    }
  }
} as const;

export type VoiceProviderCatalog = typeof voiceProviderCatalog;
export type VoiceProvider = VoiceProviderCatalog["providers"][number];
export type VoiceProviderId = VoiceProvider["id"];
export const DEFAULT_VOICE_PROVIDER_ID = voiceProviderCatalog.defaultProviderId;

