#!/usr/bin/env python3
"""Render only the curated public voice retirement references; no network or Azure reads."""
from __future__ import annotations

import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import _model_retirement as retirement
from _generator import build_parser, check_or_write

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs" / "evidence" / "voice-model-retirements.json"
TARGET = ROOT / "docs" / "region-capability-matrix.md"
START = "<!-- voice-model-retirements:start -->"
END = "<!-- voice-model-retirements:end -->"


def render_references(source: Path = SOURCE) -> str:
    records = retirement.load_public_observations(source, datetime.now(UTC))
    if not records:
        raise ValueError("Public voice retirement references must not be empty.")
    lines = [
        "### Public voice-model retirement references",
        "",
        "**Public reference dates, not live subscription or inference evidence.**",
        "Generated by `scripts/gen-voice-migration-docs.py` from",
        "`docs/evidence/voice-model-retirements.json` through the shared retirement",
        "evidence parser. The requested scope binds comparison, not availability or",
        "quota. Separately dated ARM lifecycle, SKU and inference observations may",
        "disagree; never merge them into a new date or treat this table as approval.",
        "",
        "| Model | Version | Requested comparison scope | Public retirement (UTC) | Source observed at |",
        "| --- | --- | --- | --- | --- |",
    ]
    for record in records:
        evidence = record.evidence
        if evidence.authoritative or evidence.state != "known" or evidence.qualifier != "exact":
            raise ValueError("This reference table requires exact, known public dates, not inferred deadlines.")
        lines.append(
            f"| `{record.name}` | `{record.version}` | {record.region} / {record.sku} | "
            f"{evidence.value} | {evidence.observed_at} |"
        )
    lines += ["", "Sources: " + " ".join(
        f"<{reference}>" for reference in sorted({record.evidence.reference for record in records})
    ), ""]
    return "\n".join(lines)


def render_document(document: str, source: Path = SOURCE) -> str:
    if document.count(START) != 1 or document.count(END) != 1:
        raise ValueError("Voice retirement references require exactly one marker pair.")
    before, rest = document.split(START)
    if END not in rest:
        raise ValueError("Voice retirement reference markers are out of order.")
    _, after = rest.split(END)
    return before + START + "\n" + render_references(source) + END + after


def main() -> int:
    args = build_parser(__doc__).parse_args()
    return check_or_write(
        TARGET, render_document(TARGET.read_text(encoding="utf-8")),
        regenerate_hint="Run: python scripts/gen-voice-migration-docs.py",
        check=args.check,
    )


if __name__ == "__main__":
    raise SystemExit(main())
