#!/usr/bin/env python3
"""Generate the runtime official-MCP catalog shipped inside the API image.

The API's Docker build context is ``app/api`` and therefore cannot read
``infra/mcp-servers.json`` at build time. This script projects the infrastructure
catalog (the source of truth that also drives the Bicep MCP gateway) into a
client-facing catalog bundled into the package:

    infra/mcp-servers.json  ->  app/api/src/ai4ia_api/data/official_mcp_catalog.json

The runtime catalog deliberately drops the infra-only wiring (``upstreamUrl``,
``upstreamAuthMode``, ``upstreamMiResource``) and keeps only what the backend
needs to call the server *through APIM*: a stable id, display metadata, and the
APIM route ``path`` (``<name>/mcp``). Inbound auth to APIM is always the global
APIM subscription key, so it is not encoded per entry.

Run from the repo root:  python scripts/gen-mcp-catalog.py
Verify-only (CI drift):  python scripts/gen-mcp-catalog.py --check
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE = REPO_ROOT / "infra" / "mcp-servers.json"
TARGET = REPO_ROOT / "app" / "api" / "src" / "ai4ia_api" / "data" / "official_mcp_catalog.json"

_NAME_RE = re.compile(r"^[a-z][a-z0-9-]{0,38}[a-z0-9]$")


def build_catalog(raw: dict) -> dict:
    servers = raw.get("servers", [])
    errors: list[str] = []
    seen: set[str] = set()
    items = []
    for entry in servers:
        name = entry.get("name", "")
        if not _NAME_RE.match(name):
            errors.append(f"server name '{name}' is not a valid slug (^[a-z][a-z0-9-]*[a-z0-9]$)")
        if name in seen:
            errors.append(f"duplicate server name '{name}'")
        seen.add(name)
        if not str(entry.get("upstreamUrl", "")).startswith("https://"):
            errors.append(f"{name}: upstreamUrl must be https://")
        mode = entry.get("upstreamAuthMode")
        if mode not in {"none", "managed_identity"}:
            errors.append(f"{name}: upstreamAuthMode '{mode}' must be 'none' or 'managed_identity'")
        if mode == "managed_identity" and not entry.get("upstreamMiResource"):
            errors.append(f"{name}: upstreamMiResource is required when upstreamAuthMode == managed_identity")
        items.append(
            {
                "id": name,
                "displayName": entry.get("displayName", name),
                "description": entry.get("description", ""),
                # APIM exposes the server at https://<mcp-apim>/<name>/mcp; the
                # backend composes the absolute URL from the gateway base + path.
                "path": f"{name}/mcp",
            }
        )

    if errors:
        raise SystemExit(
            "FAIL: {} issue(s) in {}:\n  - {}".format(
                len(errors), SOURCE.name, "\n  - ".join(errors)
            )
        )

    return {
        "_comment": "GENERATED by scripts/gen-mcp-catalog.py from infra/mcp-servers.json. Do not edit by hand.",
        "servers": items,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the bundled catalog is stale (no write).",
    )
    args = parser.parse_args()

    raw = json.loads(SOURCE.read_text(encoding="utf-8"))
    catalog = build_catalog(raw)
    rendered = json.dumps(catalog, indent=2) + "\n"

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(
                "official_mcp_catalog.json is stale. Run: python scripts/gen-mcp-catalog.py",
                file=sys.stderr,
            )
            return 1
        print("official_mcp_catalog.json is up to date.")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(REPO_ROOT)} ({len(catalog['servers'])} servers).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
