#!/usr/bin/env python3
"""Generate the runtime model catalog shipped inside the API image.

The API's Docker build context is ``app/api`` and therefore cannot read
``infra/models.json`` at build time. This script transforms the
infrastructure catalog (the source of truth that also drives the Bicep model
deployments) into a UI-friendly catalog bundled into the package:

    infra/models.json  ->  app/api/src/ai4ia_api/data/model_catalog.json

Each catalog entry carries the precomputed *deployment name* that matches the
Bicep naming convention, so the backend can route a request straight to the
correct Foundry deployment through the model gateway.

Run from the repo root:  python scripts/gen-model-catalog.py
Verify-only (CI drift):  python scripts/gen-model-catalog.py --check
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE = REPO_ROOT / "infra" / "models.json"
TARGET = REPO_ROOT / "app" / "api" / "src" / "ai4ia_api" / "data" / "model_catalog.json"

# Deployment-name token must match infra/main.bicep `subscriptionToken`.
SUBSCRIPTION_TOKEN = "slurmfactory"


def build_catalog(models: dict) -> dict:
    naming = models["naming"]
    sku_short = naming["skuShort"]
    regions = models["regions"]

    items = []
    for model in models["catalog"]:
        options = []
        for dep in model["deployments"]:
            region = dep["region"]
            sku = dep["sku"]
            region_meta = regions.get(region, {})
            options.append(
                {
                    "region": region,
                    "dataZone": region_meta.get("dataZone"),
                    "sku": sku,
                    "deploymentName": (
                        f"{model['name']}-{SUBSCRIPTION_TOKEN}-{region}-{sku_short[sku]}"
                    ),
                }
            )
        items.append(
            {
                "id": model["name"],
                "displayName": model.get("displayName", model["name"]),
                "category": model.get("category", "chat"),
                "format": model["format"],
                "api": model.get("api", "chat"),
                "contextWindow": model.get("contextWindow"),
                "maxOutputTokens": model.get("maxOutputTokens"),
                "options": options,
            }
        )

    return {
        "_comment": "GENERATED by scripts/gen-model-catalog.py from infra/models.json. Do not edit by hand.",
        "subscriptionToken": SUBSCRIPTION_TOKEN,
        "regions": regions,
        "models": items,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the bundled catalog is stale (no write).",
    )
    args = parser.parse_args()

    models = json.loads(SOURCE.read_text(encoding="utf-8"))
    catalog = build_catalog(models)
    rendered = json.dumps(catalog, indent=2) + "\n"

    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(
                "model_catalog.json is stale. Run: python scripts/gen-model-catalog.py",
                file=sys.stderr,
            )
            return 1
        print("model_catalog.json is up to date.")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(REPO_ROOT)} ({len(catalog['models'])} models).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
